# Generated by Django 5.2.8 on 2025-11-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
